[package]
name = "r"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.2.1"
spl-token = { version = "7.0.0", features = ["no-entrypoint"] }
mpl-token-metadata = "5.1.0"

[lib]
crate-type = ["cdylib", "lib"]
